### ISSUE TITLE
Problém při otevírání souborů v pravém panelu

### ISSUE THREAD

**Issue by DeznekCZ** [DeznekCZ/zswi_eeg_explorer_2015#19]
Je nuté zkontrolovat funčnost pro FilesIO při čtení z výstupního adresáře

**Comment by seky739** [comment]
mě to vypisuje : 
Exception in thread "AWT-EventQueue-0" java.lang.InternalError: Unable to bind C:\Users\Michal\zswi_eeg_explorer_2015\ZSWI_EEG_EXPLORER\output\Masaryko002_20141124-2.vhdr to parent
	at sun.awt.shell.Win32ShellFolder2$4.call(Win32ShellFolder2.java:414)
	at sun.awt.shell.Win32ShellFolder2$4.call(Win32ShellFolder2.java:398)
	at sun.awt.shell.Win32ShellFolderManager2$ComInvoker.invoke(Win32ShellFolderManager2.java:535)
	at sun.awt.shell.ShellFolder.invoke(ShellFolder.java:518)
	at sun.awt.shell.Win32ShellFolder2.getIShellFolder(Win32ShellFolder2.java:398)
	at sun.awt.shell.Win32ShellFolder2.access$200(Win32ShellFolder2.java:72)
	at sun.awt.shell.Win32ShellFolder2$16.call(Win32ShellFolder2.java:1095)
	at sun.awt.shell.Win32ShellFolder2$16.call(Win32ShellFolder2.java:1093)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at sun.awt.shell.Win32ShellFolderManager2$ComInvoker$3.run(Win32ShellFolderManager2.java:511)
	at java.lang.Thread.run(Thread.java:745)

TZN není chyba v app ale někde v těch managerech si myslím

**Comment by seky739** [comment]
vyřešeno otevírání do editu pouze v levém panelu
